// <auto-generated />
using System;
using HospitalPlatform.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HospitalPlatform.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HospitalDbContext))]
    partial class HospitalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("EmployeeNumberSequence");

            modelBuilder.Entity("HospitalPlatform.Api.Features.Doctors.Models.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MedicalLicenseNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Doctor");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeNumber")
                        .IsUnique();

                    b.HasIndex("MedicalLicenseNumber")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("EmployeeNumber", "UserId")
                        .IsUnique();

                    b.HasIndex("UserId", "ProfileType")
                        .IsUnique();

                    b.ToTable("Doctors", null, t =>
                        {
                            t.HasCheckConstraint("CK_Doctors_ProfileType", "\"ProfileType\" = 'Doctor'");
                        });
                });

            modelBuilder.Entity("HospitalPlatform.Api.Features.Patients.Models.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("IdentityVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("IdentityVerifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("NationalIdentificationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Patient");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdentityVerifiedByUserId");

                    b.HasIndex("NationalIdentificationNumber")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("UserId", "ProfileType")
                        .IsUnique();

                    b.ToTable("Patients", null, t =>
                        {
                            t.HasCheckConstraint("CK_Patients_IdentityVerification", "(\"IdentityVerifiedAt\" IS NULL AND \"IdentityVerifiedByUserId\" IS NULL) OR (\"IdentityVerifiedAt\" IS NOT NULL AND \"IdentityVerifiedByUserId\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_Patients_NationalIdentificationNumber", "\"NationalIdentificationNumber\" ~ '^[0-9]{8}$'");

                            t.HasCheckConstraint("CK_Patients_ProfileType", "\"ProfileType\" = 'Patient'");
                        });
                });

            modelBuilder.Entity("HospitalPlatform.Api.Features.Staff.Models.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Staff");

                    b.Property<string>("StaffRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeNumber")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("EmployeeNumber", "UserId")
                        .IsUnique();

                    b.HasIndex("UserId", "ProfileType")
                        .IsUnique();

                    b.ToTable("Staff", null, t =>
                        {
                            t.HasCheckConstraint("CK_Staff_ProfileType", "\"ProfileType\" = 'Staff'");

                            t.HasCheckConstraint("CK_Staff_StaffRole", "\"StaffRole\" IN ('Receptionist', 'Administrator')");
                        });
                });

            modelBuilder.Entity("HospitalPlatform.Api.Features.Users.Models.EmployeeNumberRegistration", b =>
                {
                    b.Property<string>("EmployeeNumber")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("EmployeeNumber");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("EmployeeNumbers", (string)null);
                });

            modelBuilder.Entity("HospitalPlatform.Api.Features.Users.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_AccountStatus", "\"AccountStatus\" IN ('PendingVerification', 'Active', 'Suspended', 'Deactivated')");

                            t.HasCheckConstraint("CK_Users_ProfileType", "\"ProfileType\" IN ('Patient', 'Doctor', 'Staff')");
                        });
                });

            modelBuilder.Entity("HospitalPlatform.Api.Features.Doctors.Models.Doctor", b =>
                {
                    b.HasOne("HospitalPlatform.Api.Features.Users.Models.EmployeeNumberRegistration", null)
                        .WithOne()
                        .HasForeignKey("HospitalPlatform.Api.Features.Doctors.Models.Doctor", "EmployeeNumber", "UserId")
                        .HasPrincipalKey("HospitalPlatform.Api.Features.Users.Models.EmployeeNumberRegistration", "EmployeeNumber", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HospitalPlatform.Api.Features.Users.Models.User", null)
                        .WithOne()
                        .HasForeignKey("HospitalPlatform.Api.Features.Doctors.Models.Doctor", "UserId", "ProfileType")
                        .HasPrincipalKey("HospitalPlatform.Api.Features.Users.Models.User", "Id", "ProfileType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HospitalPlatform.Api.Features.Patients.Models.Patient", b =>
                {
                    b.HasOne("HospitalPlatform.Api.Features.Users.Models.User", null)
                        .WithMany()
                        .HasForeignKey("IdentityVerifiedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HospitalPlatform.Api.Features.Users.Models.User", null)
                        .WithOne()
                        .HasForeignKey("HospitalPlatform.Api.Features.Patients.Models.Patient", "UserId", "ProfileType")
                        .HasPrincipalKey("HospitalPlatform.Api.Features.Users.Models.User", "Id", "ProfileType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HospitalPlatform.Api.Features.Staff.Models.Staff", b =>
                {
                    b.HasOne("HospitalPlatform.Api.Features.Users.Models.EmployeeNumberRegistration", null)
                        .WithOne()
                        .HasForeignKey("HospitalPlatform.Api.Features.Staff.Models.Staff", "EmployeeNumber", "UserId")
                        .HasPrincipalKey("HospitalPlatform.Api.Features.Users.Models.EmployeeNumberRegistration", "EmployeeNumber", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HospitalPlatform.Api.Features.Users.Models.User", null)
                        .WithOne()
                        .HasForeignKey("HospitalPlatform.Api.Features.Staff.Models.Staff", "UserId", "ProfileType")
                        .HasPrincipalKey("HospitalPlatform.Api.Features.Users.Models.User", "Id", "ProfileType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HospitalPlatform.Api.Features.Users.Models.EmployeeNumberRegistration", b =>
                {
                    b.HasOne("HospitalPlatform.Api.Features.Users.Models.User", null)
                        .WithOne()
                        .HasForeignKey("HospitalPlatform.Api.Features.Users.Models.EmployeeNumberRegistration", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
